### PR TITLE
Add Promise support for `onComplete` fn

### LINKED ISSUE #1: Promise support for `onComplete`
Hi, 

It could simplify the code if we can use the async await syntax with `onComplete` method instead of a callback.

```ts
it('should work with promises', async () => {
  const observerSpy: ObserverSpy<string> = new ObserverSpy();

  const fakeService = {
    getData() {
      return Promise.resolve('fake data');
    },
  };
  const fakeObservable = of('').pipe(switchMap(() => fakeService.getData()));

  fakeObservable.subscribe(observerSpy);

  await observerSpy.onComplete();
  expect(observerSpy.getLastValue()).toEqual('fake data');
});
```

It removes the need to use Jest `done` fn and looks more synchronous, what do you think?

### PR DESCRIPTION
**Pull request by edbzn**
Resolve #1.

I didn't updated all examples in the readme, let me know if I should.

### CODE REVIEW

**Comment by shairez** [comment]
Awesome job @edbzn !
I'll review it tomorrow

Thanks again! ❤️

**Review by shairez — APPROVED** [review]

**Comment by shairez** [comment]
@all-contributors please add @edbzn for code,test,doc,ideas

**Comment by shairez** [comment]
@all-contributors please add @edbzn for "code,test,doc,ideas"

**Comment by shairez** [comment]
@all-contributors please add @edbzn for his code tests documentation and ideas

**Comment by shairez** [comment]
Thanks @edbzn ! you are now an official contributor as well 😄 🙏 👏

**Comment by edbzn** [comment]
thank you @shairez

**Pull request merged**
