### PR TITLE
feat(observer-spy): add spyOn() utility and improved tests

### PR DESCRIPTION
**Pull request by ThomasBurleson**
Enable developers to easily spy on Observables and supports auto-unsubscribe on all spies:

*  Use `spyOn(<observable>, <completionCallback>)`
*  Use `SpyUtils.disposeAll()` to clean up in `afterEach()` tests

BREAKING CHANGE:

Revised ObserverSpy API with better support for implicit getters and prevention of state mutations. Uses Tuples to return spy instance(s) and information:

```ts
ObserverSpy<T> implements Observer {
  values: T[];                  // implicit getter
  hasValues: boolean;   // implicit getter
  isComplete: boolean; // implicit getter
  state: ObserverState; // implicit getter

  readFirst(): T;
  readLast(): T;
  freeze();
}
```

### CODE REVIEW

**Comment by shairez** [comment]
Thanks @ThomasBurleson !
Looks impressive!

This looks related to PR #8 we merged a few days ago (which added the subscribeAndSpyOn factory)

I'll put in the time this week to thoroughly go over it to understand better where they differ

Thanks again!

**Comment by ThomasBurleson** [comment]
Similar idea... this better manages that auto-subscribe AND auto-unsubscribe functionality.

I will push an update to this PR soon; one that contains documentation updates.

**Comment by ThomasBurleson** [comment]
PR updated with new `README.md` and tests combining `spyOn()`+`fakeTime()`.

**Comment by shairez** [comment]
@all-contributors please add @ThomasBurleson for their code tests documentation and ideas

**Comment by shairez** [comment]
Finally I had some time to do the merging work 😅

I wasn't able to push changes to this branch so I merged it locally and [pushed the commit](https://github.com/hirezio/observer-spy/commit/931dd689b805abb95a0c6e92dad547206c79e5a4) to master.
So I'm going to close this PR because the changes are included.
(Next time I need to figure out a way to do it and preserve the connection to the PR).

I made sure you're the author of the commit I merged.

**A lot of your great ideas were included:**

1. Auto unsubscribing

1. Shortened the name `subscribeAndSpyOn` to `subscribeSpyTo` (inspired by our conversation of shorter is better and by #15 )

1. Your improvements to the README doc, now it's much more readable.

And more...

So thank you again @ThomasBurleson for your thoughtful contribution and effort, 
you made this project better! 🙏 ❤️

**Pull request closed without merging**
